title: "Bird Flu Info"
description: "Resources to manage the ongoing 2022 - 2024 Influenza A H5N1 outbreak in the US"
remote_theme: pages-themes/minimal@v0.2.0
baseurl: "/AvianFluInfo"
plugins:
  - jekyll-remote-theme
languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["assets"]
parallel_localization: true
url: https://kenzasam.github.io/AvianFluInfo/