title: "Bird Flu Info"
description: "Resources to manage the ongoing 2022 - 2024 Influenza A H5N1 outbreak in the US"
remote_theme: pages-themes/minimal@v0.2.0
baseurl: "/AvianFluInfo"
plugins:
  - jekyll-remote-theme
  - jekyll-chatgpt-translate
last-modified-at:
    date-format: '%d-%b-%y'
chatgpt-translate:
  model: gpt-3.5-turbo
  source: en
  layout: translated
  targets: 
    - 
      language: es
      permalink: :year-:month-:day-:slug-spanish.html
      layout: spanish-translated