title: "Bird Flu Info"
description: "Resources to manage the ongoing Influenza A H5N1 outbreak"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
last-modified-at:
    date-format: '%d-%b-%y'